name: Build
on: [push, pull_request]
jobs:
  Linux-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Rust
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Release Build
        run: cargo build --release --all
      - name: Execute Tests
        run: cargo test --release --all
      - name: Run Clippy
        run: cargo clippy --release --all -- -D warnings
      - name: Check Formatting
        run: cargo fmt --all -- --check
      - name: Check Docs
        run: RUSTDOCFLAGS="-Dwarnings" cargo doc --package cuv
  Linux-MUSL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Rust
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Install MUSL Toolchain
        run: rustup target add x86_64-unknown-linux-musl
      - name: Release Build
        run: cargo build --release --all --target=x86_64-unknown-linux-musl
      - name: Execute Tests
        run: cargo test --release --all --target=x86_64-unknown-linux-musl
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Rust
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Release Build
        run: cargo build --release --all
      - name: Execute Tests
        run: cargo test --release --all
  Mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Rust
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Release Build
        run: cargo build --release --all
      - name: Execute Tests
        run: cargo test --release --all
